package io.bobba.poc.core.items;

public enum InteractionType {
	DEFAULT, GATE, TELEPORT, CURRENCY, POSTIT, ROOMEFFECT, DIMMER, TROPHY, BED, SCOREBOARD, VENDINGMACHINE, ALERT, ONEWAYGATE, LOVESHUFFLER, HABBOWHEEL, DICE, BOTTLE, RENTALS, PET, ROLLER, BALL, WATER1, WATER2, WATER3, VALSKATE, BUNNYFIELD, ELEBLOCK, WIRED, ICESKATE, BB_SCORE, BB_BLUE_GATE, BB_RED_GATE, BB_YELLOW_GATE, BB_GREEN_GATE, FRZ_TILE, FRZ_COUNTER, FBALL_GOAL, BOX, USVASHELF, FBALL_GATE, FIREWORK, LIGHTTILE, DISK, JUKEBOX, BB_TELE,
}
